language: node_js
sudo: false
node_js:
  - "8.9.4"

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

install:
  - yarn install

script:
  - yarn run coverage
  - yarn run coveralls